# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a lightweight Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default command: run the MCP server over stdio
CMD ["python", "bridge_mcp_volatility.py"]
